#!/bin/bash

sudo emerge -a \
     app-containers/docker \
     app-containers/docker-cli

sudo rc-update add docker default
sudo rc-service docker start

sudo usermod -aG docker [USER]

docker run --rm hello-world
